export const HOME = "HOME";

export const PASSANGER = "PASSANGER";
export const CREATE_PASSANGER = "CREATE_PASSANGER";
export const UPDATE_PASSANGER = "UPDATE_PASSANGER";
export const TRIPS_PASSANGER = "TRIPS_PASSANGER";
export const CREATE_TRIP = "CREATE_TRIP";

export const DRIVER = "DRIVER";
export const CREATE_DRIVER = "CREATE_DRIVER";
export const UPDATE_DRIVER = "UPDATE_DRIVER";