export const HOME = "HOME";

export const PASSENGER = "PASSENGER";
export const CREATE_PASSENGER = "CREATE_PASSENGER";
export const UPDATE_PASSENGER = "UPDATE_PASSENGER";
export const TRIPS_PASSENGER = "TRIPS_PASSENGER";
export const CREATE_TRIP = "CREATE_TRIP";

export const DRIVER = "DRIVER";
export const CREATE_DRIVER = "CREATE_DRIVER";
export const UPDATE_DRIVER = "UPDATE_DRIVER";